//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmirhanovExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngridientMenu
    {
        public int IngridientMenuId { get; set; }
        public int IngridientId { get; set; }
        public int MenuId { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Ingridients Ingridients { get; set; }
    }
}
