//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmirhanovExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingridients
    {
        public int IngridientId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Count { get; set; }
        public int SuplierId { get; set; }
    
        public virtual IngridientMenu IngridientMenu { get; set; }
        public virtual Suplier Suplier { get; set; }
    }
}
