//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmirhanovExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuEmployee
    {
        public int MenuEmployeeId { get; set; }
        public int MenuId { get; set; }
        public int EmployeeId { get; set; }
        public string Description { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
